{% set name = "pymeos-cffi" %}
{% set major = 1 %}
{% set minor = 2 %}
{% set patch = 0 %}
{% set version = major ~ '.' ~ minor ~ '.' ~ patch %}
{% set minor_version = major ~ '.' ~ minor %}
{% set next_minor_version = major ~ '.' ~ (minor + 1) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name | replace("-", "_") }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 8b490d5ed8434ed9df404404a12d58034bc02c14a1599e9db280de0367635d43

build:
  skip: true  # [win or py<37]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=61.0
    - cffi
    - pip
    - meos >={{ minor_version }},<{{ next_minor_version }}
  run:
    - python
    - cffi
    - meos >={{ minor_version }},<{{ next_minor_version }}
    - python-dateutil
    - shapely

test:
  imports:
    - pymeos_cffi
  commands:
    - pip check
    - python -c "import pymeos_cffi; pymeos_cffi.meos_initialize('UTC'); pymeos_cffi.meos_finalize();"
  requires:
    - pip

about:
  summary: Python wrapper for the MEOS C Library.
  description: |
    PyMEOS CFFI is a Python wrapper for the MEOS C Library. It wraps all the exposed functions and takes care of many
    of the necessary conversions between Python and C data types, as well as managing the errors occurring in the C
    library.
  license: PostgreSQL
  license_file: LICENSE.txt
  home: https://pymeos.readthedocs.io
  doc_url: https://pymeos.readthedocs.io
  dev_url: https://github.com/MobilityDB/PyMEOS

extra:
  recipe-maintainers:
    - Diviloper
    - estebanzimanyi
